/*
 * paywall_sites.js contains data used for the paywall bypass processing,
 * such as sites to block (stored in a blacklist)
 */

var paywallBlacklistDict = {
    "*://*.adelaidenow.com.au/*": "1",
    "*://*.baltimoresun.com/*": "1",
    "*://*.barrons.com/*": "1",
    "*://*.bloomberg.com/*": "1",
    "*://*.businessinsider.com/*": "1",
    "*://*.chicagobusiness.com/*": "1",
    "*://*.chicagotribune.com/*": "1",
    "*://*.chip.de/*": "1",
    "*://*.clarin.com/*": "1",
    "*://*.courant.com/*": "1",
    "*://*.couriermail.com.au/*": "1",
    "*://*.cricketarchive.com/*": "1",
    "*://*.dailypress.com/*": "1",
    "*://*.dailytelegraph.com.au/*": "1",
    "*://*.durangoherald.com/*": "1",
    "*://*.economist.com/*": "1",
    "*://*.fd.nl/*": "1",
    "*://*.forbes.com/*": "1",
    "*://*.ft.com/*": "1",
    "*://*.geelongadvertiser.com.au/*": "1",
    "*://*.glassdoor.com/*": "1",
    "*://*.goldcoastbulletin.com.au/*": "1",
    "*://*.haaretz.co.il/*": "1",
    "*://*.haaretz.com/*": "1",
    "*://*.hbr.org/*": "1",
    "*://*.heraldsun.com.au/*": "1",
    "*://*.inc.com/*": "1",
    "*://*.independent.co.uk/*": "1",
    "*://*.investingdaily.com/*": "1",
    "*://*.irishtimes.com/*": "1",
    "*://*.kansas.com/*": "1",
    "*://*.kansascity.com/*": "1",
    "*://*.latimes.com/*": "1",
    "*://*.lanacion.com.ar/*": "1",
    "*://*.letemps.ch/*": "1",
    "*://*.mcall.com/*": "1",
    "*://*.medium.com/*": "1",
    "*://*.medscape.com/*": "1",
    "*://*.nationalpost.com/*": "1",
    "*://*.newsweek.com/*": "1",
    "*://*.newyorker.com/*": "1",
    "*://*.nikkei.com/*": "1",
    "*://*.nrc.nl/*": "1",
    "*://*.nytimes.com/*": "1",
    "*://*.ocregister.com/*": "1",
    "*://*.orlandosentinel.com/*": "1",
    "*://*.quora.com/*": "1",
    "*://*.scmp.com/*": "1",
    "*://*.seattletimes.com/*": "1",
    "*://*.slashdot.org/*": "1",
    "*://*.smh.com.au/*": "1",
    "*://*.sun-sentinel.com/*": "1",
    "*://*.technologyreview.com/*": "1",
    "*://*.theage.com.au/*": "1",
    "*://*.theaustralian.com.au/*": "1",
    "*://*.theathletic.com/*": "1",
    "*://*.theathletic.co.uk/*": "1",
    "*://*.thenation.com/*": "1",
    "*://*.thestreet.com/*": "1",
    "*://*.thesundaytimes.co.uk/*": "1",
    "*://*.thetimes.co.uk/*": "1",
    "*://*.towardsdatascience.com/*": "1",
    "*://*.washingtonpost.com/*": "1",
    "*://*.wired.com/*": "1",
    "*://*.wsj.com/*": "1",
    "*://*.wsj.net/*": "1",
    
}

var paywallSMWhitelistDict = {
}

var paywallSpoofWhitelistDict = {
    "*://*.medium.com/*": "1",
    "*://*.towardsdatascience.com/*": "1",
    "*://*.glassdoor.com/*": "1",
    "*://*.bloomberg.com/*": "1"
}

var paywallCookieWhitelistDict = {
    "*://*.medium.com/*": "1",
    "*://*.towardsdatascience.com/*": "1",
    "*://*.nytimes.com/*": "1",
    "*://*.quora.com/*": "1",
    "*://*.wired.com/*": "1",
    "*://*.newyorker.com/*": "1",
    "*://*.theathletic.com/*": "1",
    "*://*.theathletic.co.uk/*": "1",
    "*://*.businessinsider.com/*": "1"
}